language: java
matrix:
  include:
    - os: linux
      before_script:
        - "export DISPLAY=:99.0"
        - "sh -e /etc/init.d/xvfb start"
        - sleep 3
      jdk: oraclejdk8
      addons:
        apt:
          packages:
          - oracle-java8-installer
    - os: osx
      osx_image: xcode7.3

# this is not a library, so we can prepare for testing compiling - package for good measure to be as close to install
# as possible
install: mvn package -DskipTests=true
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/b37a582210ebff5dde7c
    on_success: change
    on_failure: always
    on_start: never
